name: Build with jekyll

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1.115.1
        with:
          ruby-version: 2.7.3
          bundler-cache: true

      - name: build
        run: |
          bundle exec jekyll build
